### ISSUE TITLE
unicorn-bindings-1.0.1-r3 doesn't compile with python USE

### ISSUE THREAD

**Issue by gbmaster** [pentoo/pentoo-overlay#244]
I tried to compile unicorn-bindings with the python USE enabled, but I received the following error:

make -j5 -C python DESTDIR=/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/ install 
make: Entering directory '/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/work/unicorn-1.0.1/bindings/python'
rm -rf src/ dist/
rm -rf prebuilt/win64/unicorn.dll
rm -rf prebuilt/win32/unicorn.dll
if test -n "/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/"; then \
	python setup.py install --root="/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/"; \
else \
	python setup.py install; \
fi
running install
running build
Building C extensions
running build_py
creating build
creating build/lib
creating build/lib/unicorn
copying unicorn/__init__.py -> build/lib/unicorn
copying unicorn/sparc_const.py -> build/lib/unicorn
copying unicorn/arm64_const.py -> build/lib/unicorn
copying unicorn/mips_const.py -> build/lib/unicorn
copying unicorn/unicorn_const.py -> build/lib/unicorn
copying unicorn/m68k_const.py -> build/lib/unicorn
copying unicorn/x86_const.py -> build/lib/unicorn
copying unicorn/arm_const.py -> build/lib/unicorn
copying unicorn/unicorn.py -> build/lib/unicorn
running egg_info
creating unicorn.egg-info
writing unicorn.egg-info/PKG-INFO
writing top-level names to unicorn.egg-info/top_level.txt
writing dependency_links to unicorn.egg-info/dependency_links.txt
writing manifest file 'unicorn.egg-info/SOURCES.txt'
reading manifest file 'unicorn.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'src'
warning: no files found matching 'LICENSE.TXT'
writing manifest file 'unicorn.egg-info/SOURCES.txt'
creating build/lib/unicorn/include
creating build/lib/unicorn/include/unicorn
copying unicorn/include/unicorn/mips.h -> build/lib/unicorn/include/unicorn
copying unicorn/include/unicorn/unicorn.h -> build/lib/unicorn/include/unicorn
copying unicorn/include/unicorn/m68k.h -> build/lib/unicorn/include/unicorn
copying unicorn/include/unicorn/sparc.h -> build/lib/unicorn/include/unicorn
copying unicorn/include/unicorn/arm64.h -> build/lib/unicorn/include/unicorn
copying unicorn/include/unicorn/x86.h -> build/lib/unicorn/include/unicorn
copying unicorn/include/unicorn/arm.h -> build/lib/unicorn/include/unicorn
warning: build_py: byte-compiling is disabled, skipping.

running install_lib
creating /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr
creating /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64
creating /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7
creating /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages
creating /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
creating /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include
creating /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include/unicorn
copying build/lib/unicorn/include/unicorn/mips.h -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include/unicorn
copying build/lib/unicorn/include/unicorn/unicorn.h -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include/unicorn
copying build/lib/unicorn/include/unicorn/m68k.h -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include/unicorn
copying build/lib/unicorn/include/unicorn/sparc.h -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include/unicorn
copying build/lib/unicorn/include/unicorn/arm64.h -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include/unicorn
copying build/lib/unicorn/include/unicorn/x86.h -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include/unicorn
copying build/lib/unicorn/include/unicorn/arm.h -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn/include/unicorn
copying build/lib/unicorn/__init__.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
copying build/lib/unicorn/sparc_const.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
copying build/lib/unicorn/arm64_const.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
copying build/lib/unicorn/mips_const.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
copying build/lib/unicorn/unicorn_const.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
copying build/lib/unicorn/m68k_const.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
copying build/lib/unicorn/x86_const.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
copying build/lib/unicorn/arm_const.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
copying build/lib/unicorn/unicorn.py -> /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn
warning: install_lib: byte-compiling is disabled, skipping.

running install_egg_info
Copying unicorn.egg-info to /var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/usr/lib64/python2.7/site-packages/unicorn-1.0.1-py2.7.egg-info
running install_scripts
make: Leaving directory '/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/work/unicorn-1.0.1/bindings/python'
make -j5 -C python DESTDIR=/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/ install3 
make: Entering directory '/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/work/unicorn-1.0.1/bindings/python'
rm -rf src/ dist/
rm -rf prebuilt/win64/unicorn.dll
rm -rf prebuilt/win32/unicorn.dll
if test -n "/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/"; then \
	python3 setup.py install --root="/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/image/"; \
else \
	python3 setup.py install; \
fi
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    from setuptools.command.bdist_egg import bdist_egg
ModuleNotFoundError: No module named 'setuptools'
make: *** [Makefile:22: install3] Error 1
make: Leaving directory '/var/tmp/portage/dev-libs/unicorn-bindings-1.0.1/work/unicorn-1.0.1/bindings/python'

**Comment by blshkv** [comment]
Can you run ''"emerge - 1 setuptools'''  and try again?

**Comment by blshkv** [comment]
ok, should be fixed. Do let me know if it's not.

**Comment by gbmaster** [comment]
It still doesn't work on my side, even after an "emerge -1 setuptools"

**Comment by blshkv** [comment]
Please provide full build.log and emerge - - info, send it to https://gist.github.com

**Comment by gbmaster** [comment]
Here they are

https://gist.github.com/gbmaster/8838b5e96c308d5f6c29d3bea0f8c5b4
https://gist.github.com/gbmaster/91a3453c9191e343d811cafbd3ee8225

**Comment by blshkv** [comment]
ok, I found a typo in the ebuild, please try again.

**Comment by gbmaster** [comment]
Now I'm receiving a circular dependency error when trying to emerge both unicorn and unicorn-bindings:

emerge -1 -v unicorn
https://gist.github.com/gbmaster/8de802c779bd99383ce3e7eb91565a98

emerge -1 -v unicorn-bindings
https://gist.github.com/gbmaster/b668d175b66d9fb566ff6e1953a06961

**Comment by blshkv** [comment]
ok, fixed, please try again.

As for the main issue, I noticed that you are ~arch which means you are on your own and you expected to provide a solution together with the problem ;-)

I tried to google, and the issue is likely with you setup, see:
https://forums.gentoo.org/viewtopic-t-916336.html

You need to figure out why this module is not installed for python3 (which one?).
Make sure that you have the same python targets for setuptools (verify with ```equery f setuptools```), you have upgraded python properly and so on.

Please let me know if the bug is in our ebuild and I will be happy to fix it. 
Until then, the issue is closed

**Comment by brianmwaters** [comment]
FWIW, from when I've worked on this package in the past, I seem to recall that, while the Unicorn python bindings themselves work with both Python 2 and Python 3; the actual build and install scripts require Python 3. I haven't looked at this issue in depth at all (confirmed, latest version builds on my machine), but perhaps your problem could be related to that?

**Comment by gbmaster** [comment]
The setuptools module was not installed for Python 3.6 and I totally didn't realize this. Sorry for all the mess.

Thanks again

**Comment by blshkv** [comment]
great, good to hear!
